### ISSUE TITLE
Our feedrapp is showing German advertisement

### ISSUE THREAD

**Issue by arjankessels** [sdepold/feedrapp#100]
Suddenly our RSS-reader (uses feedrapp service) is showing German ads sometime (not every single time, only after a few screen refreshes). Example: [screenshot](https://ibb.co/MVfqW9Y)
Is this a know issue?

**Comment by sdepold** [comment]
It's not really an issue but you rather opted for supporting the project via the support query parameter. Feel free to disable it by setting the support property to false.

Would it be fine/better, if the "Mein Wunschzettel" would be translated?

**Comment by arjankessels** [comment]
Can't find how... how do i do this?

**Comment by sdepold** [comment]
Can you tell me how you call the service right now?

**Comment by sdepold** [comment]
Essentially it boils down to adding `support=false` to the query

**Comment by arjankessels** [comment]
Thanks! I've found it! This was the first time in months that i see an advertisement. Neven seen that before!
But now i've added support=false to the query.

**Comment by sdepold** [comment]
It was enabled for other languages fairly recently :)
