### ISSUE TITLE
Master branch README.md seems to point to unrelated repo for Vercel deploy

### ISSUE THREAD

**Issue by ahmogit** [sdepold/feedrapp#115]
See attached screenshot of the top-level page of this repo **(https://github.com/sdepold/feedrap).** Puzzlingly, the README.md is entitled "Nextra doc template", and the "deploy" button in under Quick Start winds up deploying  the URL associated with that Nextra repo, i.e. this one

  https://vercel.com/new/clone?s=https%3A%2F%2Fgithub.com%2Fshuding%2Fnextra-docs-template&showOptionalTeamCreation=false

rather than the feedrapp repo.  

Is this a copy-paste mistake or am I just misunderstanding what is going on?

![readme_wrong_url](https://github.com/sdepold/feedrapp/assets/5025879/24a4c4c8-1962-4355-98c8-761c60c52483)

**Comment by sdepold** [comment]
Definitely a copy paste problem :)

**Comment by sdepold** [comment]
Fixed now
