### ISSUE TITLE
how to host it on HTTPS

### ISSUE THREAD

**Issue by Vsofttech** [sdepold/feedrapp#61]
how to host it on HTTPS?? Any idea..

**Comment by carltonstith** [comment]
// will request the API via https
    // default: false
    // valid values: false, true
    ssl: true,

**Comment by carltonstith** [comment]
`$("#rss-feeds").rss(
  "http://feeds.feedburner.com/premiumpixels",
  {
// will request the API via https
// default: false
// valid values: false, true
ssl: true
})`

**Comment by sdepold** [comment]
I recently made feedrapp.info properly reachable via HTTPs. For this I created a (free) cloudfront account, added the URL to it, enabled HTTPs, pointed the respective NS DNS records of my provider to cloudfront and the CNAME records of cloudfront to heroku. I could add those steps to the readme if you want to.

**Comment by Meacho** [comment]
@Vsofttech If you open the js file under the 
`this.options = $.extend({ `
it will say `ssl: false,` change this to say  `ssl: true,`

**Comment by alexandrecvieira** [comment]
> @Vsofttech If you open the jquery.rss.js file under the
> `this.options = $.extend({ `
> it will say `ssl: false,` change this to say `ssl: true,`

I did just that and it worked, thank you
