### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by matthewjonesaus** [sdepold/feedrapp#62]
Hi - is there a way to enable CORS for feedr?

Thanks.

**Comment by futr3** [comment]
Wondering the same thing, for some reason with postman I can make requests but ajax or xhr from the browser gets blocked.  What I can I do to run this as a service for my external servers?

**Comment by sdepold-public-only** [comment]
Actually ... that's quite a good idea :)

**Comment by sdepold-public-only** [comment]
Why the hell am I even logged in with this account -.-

**Comment by mthjn** [comment]
So is there a way to enable CORS?
