### ISSUE TITLE
publishedDate returned is null though pubDate is provided

### ISSUE THREAD

**Issue by KartikDomadiya** [sdepold/feedrapp#63]
pubDate is not parsed and returned as null when we try to fetch the news from one of the RSS source having one of the item like:
<item>
            <title>Road journey in highest height</title>
            <link>http://news.google.com/something-else</link>
            <author></author>
            <pubDate>Tue, 20 Dec 2016 09:31:15 IST</pubDate>
            <publication>Udayavani - JOSHES</publication>
            <edition>Bangalore</edition>
            <keywords>Road</keywords>
            <size>1606</size>
            <ave>0</ave>
</item>

Please help.

**Comment by cavaon-wayne** [comment]
@sdepold We have the same issue, the feed we are using is https://www.smartraveller.gov.au/countries/documents/index.rss
The Feedrapp return a null, but the feed does provide a "pubDate" like this "17 Mar 2020 23:00:00 AEDT"

**Comment by cavaon-wayne** [comment]
@KartikDomadiya We change to other service to convert the RSS: https://rss2json.com/
