### ISSUE TITLE
new to git, how to install

### ISSUE THREAD

**Issue by rmakto** [sdepold/feedrapp#67]
Hello there,
I'm new to git and trying to install feedr on Heroku. I created an account with Heroku and created an app. I installed Heroku CLI on my windows 7 machine. I can login from it to git, but when I run the first "git clone git@github.com:sdepold/feedrapp.git" line, it gives me this error:

"Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct address rights and the repository exists."

Can anyone guide me on how to install this on Heroku?

**Comment by sdepold** [comment]
I updated the docs. Can you try again?

**Comment by sdepold** [comment]
The necessary steps are documented here:

- https://github.com/sdepold/feedrapp#run-your-own-feedrapp
- https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction

**Comment by rmakto** [comment]
Thanks for fixing the guide. I was able to install it afterwards.
