### ISSUE TITLE
Server Down 502 Error.

### ISSUE THREAD

**Issue by khusnetdinov** [sdepold/feedrapp#75]
Could you please check why server is down.

**Comment by bexshort** [comment]
Why the Server is down, i don't know, but you can make your own Server for this over Herokuapp.

**Comment by bexshort** [comment]
https://newstimelol.herokuapp.com/ <- This is a 1 to 1 Copy of the last Release from Feedrapp, you can too use it in your Javascript data, feedrapp.info delete and paste newstimelol.herokuapp.com and it Works. I write a Wiki Page to Create your Own Herokuapp in 10 minutes.

**Comment by sdepold** [comment]
I noticed this too and need to look into it. Unfortunately I can’t ssh into
the machine right now since I’m traveling. Will look into it ASAP
bexshort <notifications@github.com> schrieb am Do. 9. Nov. 2017 um 14:45:

**Comment by sdepold** [comment]
Actually you can find notes about hosting it yourself here: https://github.com/sdepold/feedrapp/blob/83d62130d8af5c4829851619c2047f7293a9bab8/views/index/_hosting.pug

**Comment by sdepold** [comment]
Server is back. I realized that i had a problem with my pm2 config
