### ISSUE TITLE
feedrapp.info is not working

### ISSUE THREAD

**Issue by Kirius88** [sdepold/feedrapp#91]
When trying to access the site: 
Error 520
Web server is returning an unknown error.

**Comment by sdepold** [comment]
Hey. I'm going to have a look at it today. Somehow Herold decided that my server is doing something bad and they just cancelled the entire account without notice. ...

**Comment by sdepold** [comment]
For yet unknown reasons it works again 😂

**Comment by Kirius88** [comment]
Thanks)

**Comment by testermania** [comment]
app error again.

**Comment by sdepold** [comment]
fixed. You've been quicker than my down time detector. stange.
btw it was previously down, because heroku accidentally closed random accounts.
