### ISSUE TITLE
Error en www.feedrapp.info

### ISSUE THREAD

**Issue by JahelCuadrado** [sdepold/feedrapp#98]
The web page does not load, the server is down.

**Comment by sdepold** [comment]
There is some dispute with heroku . I'll have a look later today

**Comment by sdepold** [comment]
Seems that the account is affected by this https://status.heroku.com/incidents/2386. -.-" it's the 2nd time 3 month or so

**Comment by JahelCuadrado** [comment]
:( , How can I have it locally?

**Comment by JahelCuadrado** [comment]
It works now! , but I would like to have it locally at some point

**Comment by sdepold** [comment]
I also just received the notification that my account was recovered.

**Comment by sdepold** [comment]
You can just clone the repo, install the dependencies and start the server as outlined on the website under development http://feedrapp.info/

**Comment by JahelCuadrado** [comment]
![imagen](https://user-images.githubusercontent.com/81108487/143778511-1ec93fe6-3d05-47ca-bf1a-8c96e0187652.png)

It doesn't work for me. Maybe something escapes me.

**Comment by sdepold** [comment]
Try this:

npm install
npm start

**Comment by JahelCuadrado** [comment]
![imagen](https://user-images.githubusercontent.com/81108487/143779645-fa273d39-489a-4ffa-a9f8-4c60caa7ccb1.png)

Maybe it's my problem, I don't know what can happen

**Comment by sdepold** [comment]
Well. you will need to install Node.js first it seems: https://nodejs.org/en/download/

**Comment by JahelCuadrado** [comment]
![imagen](https://user-images.githubusercontent.com/81108487/143780162-d4f97b53-6421-410e-a4f9-a90751812986.png)

**Comment by sdepold** [comment]
did you run npm install before starting it?

**Comment by JahelCuadrado** [comment]
yes

**Comment by JahelCuadrado** [comment]
![imagen](https://user-images.githubusercontent.com/81108487/143780288-3d6924b6-8e2a-414d-ae2f-37588fca736a.png)

**Comment by sdepold** [comment]
<img width="744" alt="image" src="https://user-images.githubusercontent.com/79163/143780337-84d8f269-44cd-4b14-be07-992a737c33f8.png">

try this:

```
rm -rf node_modules
npm install
npm start
```

**Comment by sdepold** [comment]
try this for yarn :https://yarnpkg.com/getting-started/install

**Comment by sdepold** [comment]
in that case you would just run 

```yarn; yarn start```

**Comment by JahelCuadrado** [comment]
![imagen](https://user-images.githubusercontent.com/81108487/143780700-02e8b1f7-ce4e-41d6-9107-1f6f34be7888.png)

:(

**Comment by sdepold** [comment]
Try with sudo?

**Comment by sdepold** [comment]
which version of node do you have?

**Comment by JahelCuadrado** [comment]
16.13

**Comment by sdepold** [comment]
sudo might work then

**Comment by JahelCuadrado** [comment]
![imagen](https://user-images.githubusercontent.com/81108487/143781061-ed95ed78-800f-4e75-8c20-616a9c042037.png)

**Comment by JahelCuadrado** [comment]
I am currently learning, thanks for your patience and help.

**Comment by JahelCuadrado** [comment]
I don't know what can happen

**Comment by sdepold** [comment]
hm. well in that case you should be able to go with this: `npm install --global yarn`

**Comment by sdepold** [comment]
afterwards yarn should be available on your system

**Comment by JahelCuadrado** [comment]
![imagen](https://user-images.githubusercontent.com/81108487/143781951-f3172fce-50d6-495e-b60a-fa6368106ffd.png)

It works, but when I put it in host, the feed does not load

![imagen](https://user-images.githubusercontent.com/81108487/143782003-f3a026cd-2453-43d0-a51d-2df904bfe5e4.png)

**Comment by sdepold** [comment]
Can you do `ssl: false`?

**Comment by sdepold** [comment]
ah and I think host needs to be only `localhost:8000`

**Comment by JahelCuadrado** [comment]
![imagen](https://user-images.githubusercontent.com/81108487/143782210-0ab8c6cc-1659-4c9f-b356-a707afe01640.png)

it works

**Comment by JahelCuadrado** [comment]
![imagen](https://user-images.githubusercontent.com/81108487/143782386-9ce75b12-d73e-49a2-8a88-4584dbdcbeb7.png)

I get this message, but it works

**Comment by sdepold** [comment]
Yeah. You can ignore that message :)

**Comment by JahelCuadrado** [comment]
Thanks :)

**Comment by sdepold** [comment]
👍

**Comment by FrutyX** [comment]
Troubles? Only temporary I hope :).

23.2.2022 - https://feedrapp.info/
![apperror](https://user-images.githubusercontent.com/23278552/155322008-92557eed-c2dd-490a-b007-b6d25412d3d3.PNG)

**Comment by sdepold** [comment]
Fixed! Sorry :)

**Comment by FrutyX** [comment]
Awesome, thank you!
